# Generated by Django 4.0.6 on 2022-07-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='describtion',
            field=models.TextField(default=''),
        ),
    ]
