# Generated by Django 4.0.6 on 2022-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_deadline_alter_project_describtion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='describtion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
